export type Negocio = {
  id: number;
  slug: string;
  nombre: string;
  cat: "tiendas" | "comer" | "actividades";
  catLabel: string;
  tags: string[];
  desc: string;
  descLarga: string;
  img: string;
  galeria: string[];
  destacado: boolean;
  horario: { dia: string; hora: string }[];
  direccion: string;
  telefono: string;
  web?: string;
  menu?: string;
  instagram?: string;
  precio?: "€" | "€€" | "€€€";
  delivery?: boolean;
};

const GALERIA_A = [
  "https://cdn.prod.website-files.com/64bb92dbd57f710d9f339706/64bb92dbd57f710d9f339819_64b7ad3f18bead3d7864b0d5_64b7aa95691cf4b2f1fb7b00_Rectangle%2525208.png",
  "https://cdn.prod.website-files.com/64bb92dbd57f710d9f339706/64bb92dbd57f710d9f339818_64b7ad3fcdc55885e4b9ca7e_64b7aa95691cf4b2f1fb7aeb_Rectangle%2525209.png",
  "https://cdn.prod.website-files.com/64bb92dbd57f710d9f339706/64bb92dbd57f710d9f339817_64b7ad3fcdc55885e4b9ca7a_64b7aa950153a186400947f1_Rectangle%25252010-1.png",
  "https://cdn.prod.website-files.com/64bb92dbd57f710d9f339706/64bb92dbd57f710d9f339816_64b7ad3ff12bc6fafbc164ea_64b7aa9512949eb74571dfed_Rectangle%25252010.png",
];

const HORARIO_STD = [
  { dia: "Lun", hora: "09:00 – 20:00" },
  { dia: "Mar", hora: "09:00 – 20:00" },
  { dia: "Mié", hora: "09:00 – 20:00" },
  { dia: "Jue", hora: "09:00 – 21:00" },
  { dia: "Vie", hora: "09:00 – 22:00" },
  { dia: "Sáb", hora: "10:00 – 22:00" },
  { dia: "Dom", hora: "10:00 – 18:00" },
];

export const NEGOCIOS: Negocio[] = [
  {
    id: 1,
    slug: "cafe-velarde",
    nombre: "Café Velarde",
    cat: "comer",
    catLabel: "Comer & Beber",
    tags: ["Terraza", "Vegano"],
    desc: "El café de especialidad favorito del barrio. Tostados de autor y ambiente acogedor para trabajar o reunirte.",
    descLarga:
      "Café Velarde nació con la misión de traer la cultura del café de especialidad al corazón del barrio. Nuestros granos, seleccionados directamente de productores de origen, se tuestan semanalmente para garantizar la máxima frescura en cada taza.\n\nEl local combina una estética cálida e industrial con una terraza soleada, perfecta para el brunch del fin de semana. Ofrecemos una carta de desayunos y almuerzos elaborada con ingredientes de temporada, además de opciones veganas y sin gluten para todos los gustos.",
    img: "https://cdn.prod.website-files.com/64bb92dbd57f710d9f339706/64bb92dbd57f710d9f339820_64b7ad4238122aabfd73d78a_64afc21b91b959274f6285db_Mask%252520group-3.png",
    galeria: GALERIA_A,
    destacado: false,
    horario: HORARIO_STD,
    direccion: "Calle Velarde 12, Madrid",
    telefono: "+34 910 123 456",
    web: "#",
    menu: "#",
    instagram: "@cafevelarde",
    precio: "€",
    delivery: false,
  },
  {
    id: 2,
    slug: "mercado-norte",
    nombre: "Mercado Norte",
    cat: "comer",
    catLabel: "Comer & Beber",
    tags: ["Música en vivo", "Vegano", "Brunch", "Wi-Fi gratis"],
    desc: "Cocina de mercado con ingredientes frescos de temporada. Menú del día y carta de tapas con producto local.",
    descLarga:
      "Mercado Norte es mucho más que un restaurante: es un punto de encuentro para los amantes de la buena comida y la cultura local. Cada semana renovamos nuestra carta según lo que ofrecen los productores de la región, garantizando ingredientes en su punto óptimo de sabor.\n\nLos jueves y viernes por la noche contamos con música en directo que transforma la experiencia en algo verdaderamente especial. Nuestra selección de vinos naturales y cervezas artesanas complementa una propuesta gastronómica honesta y comprometida con el entorno.",
    img: "https://cdn.prod.website-files.com/64bb92dbd57f710d9f339706/64bb92dbd57f710d9f33981f_64b7aee992eeacec8d341a7b_Mask%2520group.png",
    galeria: GALERIA_A,
    destacado: true,
    horario: [
      { dia: "Lun", hora: "Cerrado" },
      { dia: "Mar", hora: "13:00 – 23:00" },
      { dia: "Mié", hora: "13:00 – 23:00" },
      { dia: "Jue", hora: "13:00 – 00:00" },
      { dia: "Vie", hora: "13:00 – 00:00" },
      { dia: "Sáb", hora: "12:00 – 00:00" },
      { dia: "Dom", hora: "12:00 – 18:00" },
    ],
    direccion: "Paseo del Norte 34, Madrid",
    telefono: "+34 910 234 567",
    web: "#",
    menu: "#",
    instagram: "@mercadonorte",
    precio: "€€",
    delivery: true,
  },
  {
    id: 3,
    slug: "boveda-bistro",
    nombre: "Bóveda Bistró",
    cat: "comer",
    catLabel: "Comer & Beber",
    tags: ["Sin gluten", "Vegetariano", "Música en vivo", "Terraza"],
    desc: "Cocina mediterránea en un espacio con bóveda de piedra. Selección de vinos naturales y carta de temporada.",
    descLarga:
      "Instalado en una bodega del siglo XIX con bóvedas de ladrillo visto, Bóveda Bistró ofrece una experiencia gastronómica que combina historia y modernidad. La carta se inspira en la cocina mediterránea más honesta, con especial atención a las opciones vegetarianas y sin gluten.\n\nLos fines de semana, el espacio se convierte en escenario para músicos locales que crean el ambiente perfecto para una cena especial. La terraza interior, protegida y luminosa, está disponible todo el año.",
    img: "https://cdn.prod.website-files.com/64bb92dbd57f710d9f339706/64bb92dbd57f710d9f339821_64b7ad42cb0b1ad4dd4c7292_64afc2300502866d088e5da5_Mask%252520group-8.png",
    galeria: GALERIA_A,
    destacado: false,
    horario: HORARIO_STD,
    direccion: "Calle de la Paloma 8, Madrid",
    telefono: "+34 910 345 678",
    web: "#",
    menu: "#",
    instagram: "@bovedabistro",
    precio: "€€€",
    delivery: false,
  },
  {
    id: 4,
    slug: "la-roja-canteen",
    nombre: "La Roja Canteen",
    cat: "comer",
    catLabel: "Comer & Beber",
    tags: ["Música en vivo", "Sin gluten"],
    desc: "Tapas y raciones en un ambiente informal. Tertulia garantizada los jueves con música en directo.",
    descLarga:
      "La Roja Canteen es el tipo de lugar donde el tiempo pasa sin que te des cuenta. Raciones generosas, vinos de la tierra y una barra siempre animada hacen de este rincón un favorito del barrio desde que abrió sus puertas.\n\nCada jueves organizamos una sesión de música en directo con artistas locales. Los productos sin gluten están claramente identificados en la carta, y el equipo siempre está dispuesto a adaptar los platos.",
    img: "https://cdn.prod.website-files.com/64bb92dbd57f710d9f339706/64bb92dbd57f710d9f33981d_64b7ad407810eb4f16635b12_64afc2c522f7af85561c5d42_Mask%252520group-5.png",
    galeria: GALERIA_A,
    destacado: false,
    horario: HORARIO_STD,
    direccion: "Calle Amparo 56, Madrid",
    telefono: "+34 910 456 789",
    web: "#",
    instagram: "@larojacanteen",
    precio: "€€",
    delivery: false,
  },
  {
    id: 5,
    slug: "pradera-roadhouse",
    nombre: "Pradera Roadhouse",
    cat: "comer",
    catLabel: "Comer & Beber",
    tags: ["Brunch", "Wi-Fi gratis"],
    desc: "Brunch americano con toque local. Pancakes, eggs benedict y los mejores bloody marys del barrio.",
    descLarga:
      "Pradera Roadhouse reimagina el brunch americano con ingredientes locales y mucho cariño. Los pancakes con maple syrup de producción propia, los eggs benedict con jamón ibérico y los bloody marys con especias de la tierra son solo algunos de los imprescindibles.\n\nEl espacio, amplio y luminoso, cuenta con Wi-Fi gratuito para los que quieren convertir el brunch en una mañana productiva. Reservas disponibles para grupos de más de 6 personas.",
    img: "https://cdn.prod.website-files.com/64bb92dbd57f710d9f339706/64bb92dbd57f710d9f33981e_64b7ad41d29c585c54f190b7_64afc2d7376d3438a77c3573_Mask%252520group-7.png",
    galeria: GALERIA_A,
    destacado: false,
    horario: [
      { dia: "Lun", hora: "Cerrado" },
      { dia: "Mar", hora: "Cerrado" },
      { dia: "Mié", hora: "09:00 – 17:00" },
      { dia: "Jue", hora: "09:00 – 17:00" },
      { dia: "Vie", hora: "09:00 – 17:00" },
      { dia: "Sáb", hora: "09:00 – 18:00" },
      { dia: "Dom", hora: "09:00 – 18:00" },
    ],
    direccion: "Calle del Pez 22, Madrid",
    telefono: "+34 910 567 890",
    web: "#",
    menu: "#",
    instagram: "@praderaroadhouse",
    precio: "€€",
    delivery: true,
  },
  {
    id: 6,
    slug: "el-conejo-inquieto",
    nombre: "El Conejo Inquieto",
    cat: "comer",
    catLabel: "Comer & Beber",
    tags: ["Admite mascotas", "Wi-Fi gratis"],
    desc: "Ristorante de barrio con ambiente familiar. Pastas frescas artesanales y pizzas de masa madre.",
    descLarga:
      "El Conejo Inquieto es el italiano del barrio que todos queremos tener cerca: pastas frescas hechas a diario, pizzas de masa madre con 48 horas de fermentación y una carta de vinos italianos seleccionados con criterio.\n\nAdmitimos mascotas en la terraza y contamos con Wi-Fi gratuito en todo el local. El ambiente es relajado y familiar, ideal tanto para cenas románticas como para reuniones con amigos.",
    img: "https://cdn.prod.website-files.com/64bb92dbd57f710d9f339706/64bb92dbd57f710d9f33982b_64b7ae4b29a9c0d18bc1925d_Mask%2520group-1.png",
    galeria: GALERIA_A,
    destacado: true,
    horario: HORARIO_STD,
    direccion: "Calle Fuencarral 88, Madrid",
    telefono: "+34 910 678 901",
    web: "#",
    menu: "#",
    instagram: "@elconejoinquieto",
    precio: "€€",
    delivery: true,
  },
  {
    id: 7,
    slug: "studio-indigo",
    nombre: "Studio Índigo",
    cat: "tiendas",
    catLabel: "Tiendas",
    tags: ["Sin gluten", "Música en vivo", "Vegano", "Brunch"],
    desc: "Moda y accesorios de diseñadores locales emergentes. Prendas únicas con historia y materiales sostenibles.",
    descLarga:
      "Studio Índigo es el espacio donde los diseñadores locales emergentes dan a conocer su trabajo. Cada pieza que encontrarás aquí está hecha con materiales sostenibles y cuenta la historia de quien la creó.\n\nOrganizamos eventos mensuales donde los diseñadores presentan sus nuevas colecciones. También ofrecemos servicio de personalización para quienes buscan una prenda verdaderamente única.",
    img: "https://cdn.prod.website-files.com/64bb92dbd57f710d9f339706/64bb92dbd57f710d9f33981b_64b7ad40cdc55885e4b9ca8b_64afc2f1dcfbd99e52ea634d_Mask%252520group-2.png",
    galeria: GALERIA_A,
    destacado: false,
    horario: HORARIO_STD,
    direccion: "Calle Hortaleza 45, Madrid",
    telefono: "+34 910 789 012",
    web: "#",
    instagram: "@studioindigo",
    precio: "€€€",
  },
  {
    id: 8,
    slug: "libreria-el-farol",
    nombre: "Librería El Farol",
    cat: "tiendas",
    catLabel: "Tiendas",
    tags: ["Admite mascotas", "Brunch"],
    desc: "Librería independiente con café, zona de lectura y presentaciones de autores locales cada semana.",
    descLarga:
      "El Farol es la librería de barrio que creíamos extintas. Selección cuidada de títulos en castellano y otras lenguas, espacio de lectura con butacas cómodas, y un pequeño café donde disfrutar de la experiencia completa.\n\nCada sábado por la tarde organizamos presentaciones de autores locales y clubes de lectura. Las mascotas son bienvenidas en el espacio, siempre que sean tan tranquilas como los libros que nos rodean.",
    img: "https://cdn.prod.website-files.com/64bb92dbd57f710d9f339706/64bb92dbd57f710d9f33982d_64b7aea93c2fddec6fdd11b2_Mask%2520group-4.png",
    galeria: GALERIA_A,
    destacado: false,
    horario: [
      { dia: "Lun", hora: "10:00 – 20:00" },
      { dia: "Mar", hora: "10:00 – 20:00" },
      { dia: "Mié", hora: "10:00 – 20:00" },
      { dia: "Jue", hora: "10:00 – 20:00" },
      { dia: "Vie", hora: "10:00 – 21:00" },
      { dia: "Sáb", hora: "10:00 – 21:00" },
      { dia: "Dom", hora: "11:00 – 15:00" },
    ],
    direccion: "Calle San Bernardino 3, Madrid",
    telefono: "+34 910 890 123",
    web: "#",
    instagram: "@libreriaelfaro",
    precio: "€",
  },
  {
    id: 9,
    slug: "casa-rooster",
    nombre: "Casa Rooster",
    cat: "tiendas",
    catLabel: "Tiendas",
    tags: ["Vegetariano", "Terraza", "Wi-Fi gratis", "Vegano", "Admite mascotas"],
    desc: "Tienda de productos artesanales, especias, conservas y delicatessen de productores locales.",
    descLarga:
      "Casa Rooster es una tienda de delicatessen con alma de mercado. Aquí encontrarás aceites de oliva virgen extra de prensado en frío, conservas artesanales, quesos de pequeños productores y especias traídas directamente de sus países de origen.\n\nOrganizamos catas y talleres de cocina mensuales para quienes quieren aprender a sacar el máximo partido a los mejores ingredientes. La terraza exterior es perfecta para degustar nuestras tapas de temporada.",
    img: "https://cdn.prod.website-files.com/64bb92dbd57f710d9f339706/64bb92dbd57f710d9f33982a_64b7afac500e0f611f6749fd_Mask%2520group-2.png",
    galeria: GALERIA_A,
    destacado: false,
    horario: HORARIO_STD,
    direccion: "Calle Manuela Malasaña 16, Madrid",
    telefono: "+34 910 901 234",
    web: "#",
    instagram: "@casarooster",
    precio: "€€",
  },
  {
    id: 10,
    slug: "galeria-lumen",
    nombre: "Galería Lumen",
    cat: "actividades",
    catLabel: "Actividades",
    tags: ["Vegetariano", "Wi-Fi gratis"],
    desc: "Espacio cultural con exposiciones temporales, talleres de arte y eventos creativos cada fin de semana.",
    descLarga:
      "Galería Lumen es un espacio vivo dedicado al arte contemporáneo y la cultura visual. Cada mes presentamos una nueva exposición de artistas emergentes y consolidados, acompañada de un programa de actividades paralelas: visitas guiadas, charlas con los artistas y talleres prácticos.\n\nLos fines de semana organizamos talleres para todos los niveles: pintura, fotografía, ilustración, serigrafía. El espacio también está disponible para eventos privados y presentaciones corporativas.",
    img: "https://cdn.prod.website-files.com/64bb92dbd57f710d9f339706/64bb92dbd57f710d9f33982e_64b7aeb244695f5583d19381_Mask%2520group-5.png",
    galeria: GALERIA_A,
    destacado: false,
    horario: [
      { dia: "Lun", hora: "Cerrado" },
      { dia: "Mar", hora: "12:00 – 20:00" },
      { dia: "Mié", hora: "12:00 – 20:00" },
      { dia: "Jue", hora: "12:00 – 20:00" },
      { dia: "Vie", hora: "12:00 – 21:00" },
      { dia: "Sáb", hora: "11:00 – 21:00" },
      { dia: "Dom", hora: "11:00 – 17:00" },
    ],
    direccion: "Calle del Barco 19, Madrid",
    telefono: "+34 910 012 345",
    web: "#",
    instagram: "@galerialumen",
    precio: "€€",
  },
  {
    id: 11,
    slug: "boveda-climbing",
    nombre: "Bóveda Climbing",
    cat: "actividades",
    catLabel: "Actividades",
    tags: ["Vegano"],
    desc: "El rocódromo indoor más completo de la ciudad. Rutas para todos los niveles y clases grupales al atardecer.",
    descLarga:
      "Bóveda Climbing es el rocódromo de referencia en la ciudad. Con más de 200 rutas de dificultad variada y paredes de hasta 15 metros, es el lugar ideal tanto para iniciarse como para progresar en la escalada.\n\nOfrecemos clases grupales e individuales, alquiler de material y zona de entrenamiento específico. El equipo de monitores certificados está siempre disponible para guiarte en tu progresión. Los niños a partir de 6 años son bienvenidos en nuestras clases familiares de los sábados.",
    img: "https://cdn.prod.website-files.com/64bb92dbd57f710d9f339706/64bb92dbd57f710d9f33982f_64b7aedb7c0010e65f19d142_Mask%2520group-6.png",
    galeria: GALERIA_A,
    destacado: false,
    horario: [
      { dia: "Lun", hora: "07:00 – 23:00" },
      { dia: "Mar", hora: "07:00 – 23:00" },
      { dia: "Mié", hora: "07:00 – 23:00" },
      { dia: "Jue", hora: "07:00 – 23:00" },
      { dia: "Vie", hora: "07:00 – 22:00" },
      { dia: "Sáb", hora: "09:00 – 21:00" },
      { dia: "Dom", hora: "09:00 – 20:00" },
    ],
    direccion: "Calle de Bravo Murillo 120, Madrid",
    telefono: "+34 910 123 789",
    web: "#",
    instagram: "@bovedaclimbing",
    precio: "€€",
  },
  {
    id: 12,
    slug: "la-terraza-rooftop",
    nombre: "La Terraza Rooftop",
    cat: "actividades",
    catLabel: "Actividades",
    tags: ["Admite mascotas", "Terraza", "Sin gluten", "Vegetariano"],
    desc: "El rooftop más especial de la ciudad. Vistas panorámicas, cócteles de autor y música los viernes.",
    descLarga:
      "La Terraza Rooftop es el destino perfecto para despedir la semana con estilo. Situada en la séptima planta con vistas de 360° sobre la ciudad, ofrece una experiencia única que combina coctelería de autor, pequeños platos y música en directo cada viernes y sábado.\n\nLa carta de cócteles, diseñada por nuestro head bartender, cambia con las estaciones para aprovechar los mejores ingredientes de temporada. Admitimos mascotas en toda la terraza exterior y contamos con opciones sin gluten y vegetarianas en toda la carta.",
    img: "https://cdn.prod.website-files.com/64bb92dbd57f710d9f339706/64bb92dbd57f710d9f33982b_64b7ae4b29a9c0d18bc1925d_Mask%2520group-1.png",
    galeria: GALERIA_A,
    destacado: true,
    horario: [
      { dia: "Lun", hora: "Cerrado" },
      { dia: "Mar", hora: "Cerrado" },
      { dia: "Mié", hora: "18:00 – 00:00" },
      { dia: "Jue", hora: "18:00 – 01:00" },
      { dia: "Vie", hora: "18:00 – 02:00" },
      { dia: "Sáb", hora: "16:00 – 02:00" },
      { dia: "Dom", hora: "16:00 – 23:00" },
    ],
    direccion: "Calle Gran Vía 35, Planta 7, Madrid",
    telefono: "+34 910 234 890",
    web: "#",
    instagram: "@laterrazarooftop",
    precio: "€€€",
  },
];

export const CATS = [
  { id: "tiendas", label: "Tiendas" },
  { id: "comer", label: "Comer & Beber" },
  { id: "actividades", label: "Actividades" },
] as const;

export const TAGS_RAPIDOS = ["A domicilio", "Delivery disponible"];

export const TAGS_EXTRA = [
  "Admite mascotas",
  "Wi-Fi gratis",
  "Música en vivo",
  "Brunch",
  "Vegano",
  "Vegetariano",
  "Sin gluten",
  "Terraza",
];
